import { readFile, writeFile } from "node:fs/promises";
import { createThemeTokens, themePresets } from "../src/lib/theme/theme";

const globals = await readFile(
  new URL("../src/styles/globals.css", import.meta.url),
  "utf8",
);
function readTokens(selector: RegExp): Record<string, string> {
  const content = globals.match(selector)?.[1];
  if (!content) throw new Error("Missing shared default tokens");
  return Object.fromEntries(
    [...content.matchAll(/(--[\w-]+):\s*([^;]+);/g)]
      .filter((match) => match[1] !== "--radius")
      .map((match) => [match[1], match[2].trim()]),
  );
}
const light = readTokens(/^:root \{([^}]+)\}/m);
const dark = { ...light, ...readTokens(/^\.dark \{([^}]+)\}/m) };
for (const theme of themePresets) {
  const lightSelectors = `:root[data-color="${theme.id}"],\n[data-color="${theme.id}"]`;
  const darkSelectors = `:root.dark[data-color="${theme.id}"],\n.dark [data-color="${theme.id}"],\n[data-color="${theme.id}"].dark`;
  const declarations = (tokens: Record<string, string>) =>
    Object.entries(tokens)
      .map(([key, value]) => `  ${key}: ${value};`)
      .join("\n");
  const content = `/* Generated by bun run themes:generate from the shared default tokens and theme definitions. */\n${lightSelectors} {\n${declarations({ ...light, ...createThemeTokens(theme.color, false) })}\n}\n\n${darkSelectors} {\n${declarations({ ...dark, ...createThemeTokens(theme.color, true) })}\n}\n`;
  await writeFile(
    new URL(`../src/styles/themes/${theme.id}.css`, import.meta.url),
    content,
  );
}
