/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LangChar125RouteImport } from './routes/{-$lang}'
import { Route as ApiLlmsMarkdownRouteImport } from './routes/api.llms-markdown'
import { Route as ApiMarkdownRouteImport } from './routes/api.markdown'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}.index'
import { Route as Char123LangChar125LlmsFullDottxtRouteImport } from './routes/{-$lang}.llms-full[.]txt'
import { Route as Char123LangChar125LlmsDottxtRouteImport } from './routes/{-$lang}.llms[.]txt'
import { Route as Char123LangChar125DocsSplatRouteImport } from './routes/{-$lang}.docs.$'

const Char123LangChar125Route = Char123LangChar125RouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmsMarkdownRoute = ApiLlmsMarkdownRouteImport.update({
  id: '/api/llms-markdown',
  path: '/api/llms-markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarkdownRoute = ApiMarkdownRouteImport.update({
  id: '/api/markdown',
  path: '/api/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125LlmsFullDottxtRoute =
  Char123LangChar125LlmsFullDottxtRouteImport.update({
    id: '/llms-full.txt',
    path: '/llms-full.txt',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125LlmsDottxtRoute =
  Char123LangChar125LlmsDottxtRouteImport.update({
    id: '/llms.txt',
    path: '/llms.txt',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125DocsSplatRoute =
  Char123LangChar125DocsSplatRouteImport.update({
    id: '/docs/$',
    path: '/docs/$',
    getParentRoute: () => Char123LangChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$lang}': typeof Char123LangChar125RouteWithChildren
  '/api/llms-markdown': typeof ApiLlmsMarkdownRoute
  '/api/markdown': typeof ApiMarkdownRoute
  '/api/search': typeof ApiSearchRoute
  '/{-$lang}/llms-full.txt': typeof Char123LangChar125LlmsFullDottxtRoute
  '/{-$lang}/llms.txt': typeof Char123LangChar125LlmsDottxtRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
}
export interface FileRoutesByTo {
  '/api/llms-markdown': typeof ApiLlmsMarkdownRoute
  '/api/markdown': typeof ApiMarkdownRoute
  '/api/search': typeof ApiSearchRoute
  '/{-$lang}/llms-full.txt': typeof Char123LangChar125LlmsFullDottxtRoute
  '/{-$lang}/llms.txt': typeof Char123LangChar125LlmsDottxtRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lang}': typeof Char123LangChar125RouteWithChildren
  '/api/llms-markdown': typeof ApiLlmsMarkdownRoute
  '/api/markdown': typeof ApiMarkdownRoute
  '/api/search': typeof ApiSearchRoute
  '/{-$lang}/llms-full.txt': typeof Char123LangChar125LlmsFullDottxtRoute
  '/{-$lang}/llms.txt': typeof Char123LangChar125LlmsDottxtRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lang}'
    | '/api/llms-markdown'
    | '/api/markdown'
    | '/api/search'
    | '/{-$lang}/llms-full.txt'
    | '/{-$lang}/llms.txt'
    | '/{-$lang}/'
    | '/{-$lang}/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/llms-markdown'
    | '/api/markdown'
    | '/api/search'
    | '/{-$lang}/llms-full.txt'
    | '/{-$lang}/llms.txt'
    | '/{-$lang}'
    | '/{-$lang}/docs/$'
  id:
    | '__root__'
    | '/{-$lang}'
    | '/api/llms-markdown'
    | '/api/markdown'
    | '/api/search'
    | '/{-$lang}/llms-full.txt'
    | '/{-$lang}/llms.txt'
    | '/{-$lang}/'
    | '/{-$lang}/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LangChar125Route: typeof Char123LangChar125RouteWithChildren
  ApiLlmsMarkdownRoute: typeof ApiLlmsMarkdownRoute
  ApiMarkdownRoute: typeof ApiMarkdownRoute
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llms-markdown': {
      id: '/api/llms-markdown'
      path: '/api/llms-markdown'
      fullPath: '/api/llms-markdown'
      preLoaderRoute: typeof ApiLlmsMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markdown': {
      id: '/api/markdown'
      path: '/api/markdown'
      fullPath: '/api/markdown'
      preLoaderRoute: typeof ApiMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/llms-full.txt': {
      id: '/{-$lang}/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/{-$lang}/llms-full.txt'
      preLoaderRoute: typeof Char123LangChar125LlmsFullDottxtRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/llms.txt': {
      id: '/{-$lang}/llms.txt'
      path: '/llms.txt'
      fullPath: '/{-$lang}/llms.txt'
      preLoaderRoute: typeof Char123LangChar125LlmsDottxtRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/docs/$': {
      id: '/{-$lang}/docs/$'
      path: '/docs/$'
      fullPath: '/{-$lang}/docs/$'
      preLoaderRoute: typeof Char123LangChar125DocsSplatRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
  }
}

interface Char123LangChar125RouteChildren {
  Char123LangChar125LlmsFullDottxtRoute: typeof Char123LangChar125LlmsFullDottxtRoute
  Char123LangChar125LlmsDottxtRoute: typeof Char123LangChar125LlmsDottxtRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125DocsSplatRoute: typeof Char123LangChar125DocsSplatRoute
}

const Char123LangChar125RouteChildren: Char123LangChar125RouteChildren = {
  Char123LangChar125LlmsFullDottxtRoute: Char123LangChar125LlmsFullDottxtRoute,
  Char123LangChar125LlmsDottxtRoute: Char123LangChar125LlmsDottxtRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  Char123LangChar125DocsSplatRoute: Char123LangChar125DocsSplatRoute,
}

const Char123LangChar125RouteWithChildren =
  Char123LangChar125Route._addFileChildren(Char123LangChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LangChar125Route: Char123LangChar125RouteWithChildren,
  ApiLlmsMarkdownRoute: ApiLlmsMarkdownRoute,
  ApiMarkdownRoute: ApiMarkdownRoute,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
