import type { TableLabels } from "@workspace/ui/blocks/data-table";

/** Translations belong to the consuming application. */
export const chineseTableLabels: TableLabels = {
  sortAscending: "升序",
  sortDescending: "降序",
  clearSorting: "清除排序",
  hideColumn: "隐藏列",
  columns: "列设置",
  density: "密度",
  dragReorder: "拖拽排序",
  loadFailed: "加载失败，请重试",
  noData: "暂无数据",
  pinEnd: "固定到末尾",
  pinStart: "固定到起始",
  refresh: "刷新",
  retry: "重试",
  loading: "正在加载数据…",
  reorderRows: "调整顺序",
  reset: "重置",
  search: "搜索",
  searchPlaceholder: (column: string) => `搜索${column}`,
  sizeComfortable: "舒适",
  sizeCompact: "紧凑",
  sizeMedium: "适中",
  unpinEnd: "取消末尾固定",
  unpinStart: "取消起始固定",
  selectClear: "清除选择",
  selectSearch: "搜索",
  selectNoResults: "无匹配项",
  bulkAnnouncement: (count: number) => `已选择 ${count} 行，可使用批量操作`,
  bulkToolbar: (count: number) => `${count} 行的批量操作`,
  bulkClearSelection: "清除选择（Escape）",
  bulkSelectedRows: () => "行已选中",
  paginationFirstPage: "首页",
  paginationLastPage: "末页",
  paginationMorePages: "更多页",
  paginationNextPage: "下一页",
  paginationPage: (page: number) => `第 ${page} 页`,
  paginationPreviousPage: "上一页",
  paginationRows: "每页行数",
  paginationLoadedRows: (count: number) => `当前页 ${count} 条`,
  paginationTotalRows: (total: number) => `共 ${total} 条`,
};
