import type { ComponentType } from "react";
import type { ExampleProps } from "./types";

export const examples = {
  "long-text-demo": () => import("./variants/long-text-demo"),
  "long-text-table": () => import("./variants/long-text-table"),
  "navigation-progress-demo": () =>
    import("./variants/navigation-progress-demo"),
  "block-table-header": () => import("./variants/block-table-header"),
  "block-table-search": () => import("./variants/block-table-search"),
  "block-table-layout": () => import("./variants/block-table-layout"),
  "block-table-demo": () => import("./variants/block-table-demo"),
  "block-table-selection": () => import("./variants/block-table-selection"),
  "block-table-drag": () => import("./variants/block-table-drag"),
  "block-table-request": () => import("./variants/block-table-request"),
  "block-table-states": () => import("./variants/block-table-states"),
  "block-form-report": () => import("./variants/block-form-report"),
  "block-form-profile": () => import("./variants/block-form-profile"),
  "block-delete-resource": () => import("./variants/block-delete-resource"),
  "block-delete-resource-error": () =>
    import("./variants/block-delete-resource-error"),
  "block-delete-resource-insensitive": () =>
    import("./variants/block-delete-resource-insensitive"),
  "accordion-basic": () => import("./variants/accordion-basic"),
  "accordion-borders": () => import("./variants/accordion-borders"),
  "accordion-card": () => import("./variants/accordion-card"),
  "accordion-demo": () => import("./variants/accordion-demo"),
  "accordion-disabled": () => import("./variants/accordion-disabled"),
  "accordion-multiple": () => import("./variants/accordion-multiple"),
  "accordion-rtl": () => import("./variants/accordion-rtl"),
  "alert-action": () => import("./variants/alert-action"),
  "alert-basic": () => import("./variants/alert-basic"),
  "alert-colors": () => import("./variants/alert-colors"),
  "alert-demo": () => import("./variants/alert-demo"),
  "alert-destructive": () => import("./variants/alert-destructive"),
  "alert-dialog-basic": () => import("./variants/alert-dialog-basic"),
  "alert-dialog-demo": () => import("./variants/alert-dialog-demo"),
  "alert-dialog-destructive": () =>
    import("./variants/alert-dialog-destructive"),
  "alert-dialog-media": () => import("./variants/alert-dialog-media"),
  "alert-dialog-rtl": () => import("./variants/alert-dialog-rtl"),
  "alert-dialog-small": () => import("./variants/alert-dialog-small"),
  "alert-dialog-small-media": () =>
    import("./variants/alert-dialog-small-media"),
  "alert-rtl": () => import("./variants/alert-rtl"),
  "aspect-ratio-demo": () => import("./variants/aspect-ratio-demo"),
  "aspect-ratio-portrait": () => import("./variants/aspect-ratio-portrait"),
  "aspect-ratio-rtl": () => import("./variants/aspect-ratio-rtl"),
  "aspect-ratio-square": () => import("./variants/aspect-ratio-square"),
  "attachment-demo": () => import("./variants/attachment-demo"),
  "attachment-group": () => import("./variants/attachment-group"),
  "attachment-image": () => import("./variants/attachment-image"),
  "attachment-sizes": () => import("./variants/attachment-sizes"),
  "attachment-states": () => import("./variants/attachment-states"),
  "attachment-trigger": () => import("./variants/attachment-trigger"),
  "autocomplete-demo": () => import("./variants/autocomplete-demo"),
  "autocomplete-disabled": () => import("./variants/autocomplete-disabled"),
  "autocomplete-grouped": () => import("./variants/autocomplete-grouped"),
  "avatar-badge": () => import("./variants/avatar-badge"),
  "avatar-badge-icon": () => import("./variants/avatar-badge-icon"),
  "avatar-basic": () => import("./variants/avatar-basic"),
  "avatar-demo": () => import("./variants/avatar-demo"),
  "avatar-dropdown": () => import("./variants/avatar-dropdown"),
  "avatar-group": () => import("./variants/avatar-group"),
  "avatar-group-count": () => import("./variants/avatar-group-count"),
  "avatar-group-count-icon": () => import("./variants/avatar-group-count-icon"),
  "avatar-rtl": () => import("./variants/avatar-rtl"),
  "avatar-size": () => import("./variants/avatar-size"),
  "badge-colors": () => import("./variants/badge-colors"),
  "badge-demo": () => import("./variants/badge-demo"),
  "badge-icon": () => import("./variants/badge-icon"),
  "badge-link": () => import("./variants/badge-link"),
  "badge-loading": () => import("./variants/badge-loading"),
  "badge-rtl": () => import("./variants/badge-rtl"),
  "badge-variants": () => import("./variants/badge-variants"),
  "breadcrumb-basic": () => import("./variants/breadcrumb-basic"),
  "breadcrumb-demo": () => import("./variants/breadcrumb-demo"),
  "breadcrumb-dropdown": () => import("./variants/breadcrumb-dropdown"),
  "breadcrumb-ellipsis": () => import("./variants/breadcrumb-ellipsis"),
  "breadcrumb-link": () => import("./variants/breadcrumb-link"),
  "breadcrumb-rtl": () => import("./variants/breadcrumb-rtl"),
  "breadcrumb-separator": () => import("./variants/breadcrumb-separator"),
  "bubble-alignment": () => import("./variants/bubble-alignment"),
  "bubble-collapsible": () => import("./variants/bubble-collapsible"),
  "bubble-demo": () => import("./variants/bubble-demo"),
  "bubble-group-demo": () => import("./variants/bubble-group-demo"),
  "bubble-link-button": () => import("./variants/bubble-link-button"),
  "bubble-popover": () => import("./variants/bubble-popover"),
  "bubble-reactions": () => import("./variants/bubble-reactions"),
  "bubble-tooltip": () => import("./variants/bubble-tooltip"),
  "bubble-variants": () => import("./variants/bubble-variants"),
  "button-default": () => import("./variants/button-default"),
  "button-demo": () => import("./variants/button-demo"),
  "button-destructive": () => import("./variants/button-destructive"),
  "button-ghost": () => import("./variants/button-ghost"),
  "button-group-demo": () => import("./variants/button-group-demo"),
  "button-group-dropdown": () => import("./variants/button-group-dropdown"),
  "button-group-input": () => import("./variants/button-group-input"),
  "button-group-input-group": () =>
    import("./variants/button-group-input-group"),
  "button-group-nested": () => import("./variants/button-group-nested"),
  "button-group-orientation": () =>
    import("./variants/button-group-orientation"),
  "button-group-popover": () => import("./variants/button-group-popover"),
  "button-group-rtl": () => import("./variants/button-group-rtl"),
  "button-group-select": () => import("./variants/button-group-select"),
  "button-group-separator": () => import("./variants/button-group-separator"),
  "button-group-size": () => import("./variants/button-group-size"),
  "button-group-split": () => import("./variants/button-group-split"),
  "button-icon": () => import("./variants/button-icon"),
  "button-link": () => import("./variants/button-link"),
  "button-loading": () => import("./variants/button-loading"),
  "button-outline": () => import("./variants/button-outline"),
  "button-render": () => import("./variants/button-render"),
  "button-rounded": () => import("./variants/button-rounded"),
  "button-rtl": () => import("./variants/button-rtl"),
  "button-secondary": () => import("./variants/button-secondary"),
  "button-size": () => import("./variants/button-size"),
  "button-with-icon": () => import("./variants/button-with-icon"),
  "calendar-basic": () => import("./variants/calendar-basic"),
  "calendar-booked-dates": () => import("./variants/calendar-booked-dates"),
  "calendar-caption": () => import("./variants/calendar-caption"),
  "calendar-custom-days": () => import("./variants/calendar-custom-days"),
  "calendar-demo": () => import("./variants/calendar-demo"),
  "calendar-hijri": () => import("./variants/calendar-hijri"),
  "calendar-presets": () => import("./variants/calendar-presets"),
  "calendar-range": () => import("./variants/calendar-range"),
  "calendar-rtl": () => import("./variants/calendar-rtl"),
  "calendar-time": () => import("./variants/calendar-time"),
  "calendar-week-numbers": () => import("./variants/calendar-week-numbers"),
  "card-demo": () => import("./variants/card-demo"),
  "card-edge-to-edge": () => import("./variants/card-edge-to-edge"),
  "card-image": () => import("./variants/card-image"),
  "card-rtl": () => import("./variants/card-rtl"),
  "card-small": () => import("./variants/card-small"),
  "card-spacing": () => import("./variants/card-spacing"),
  "carousel-api": () => import("./variants/carousel-api"),
  "carousel-demo": () => import("./variants/carousel-demo"),
  "carousel-orientation": () => import("./variants/carousel-orientation"),
  "carousel-plugin": () => import("./variants/carousel-plugin"),
  "carousel-rtl": () => import("./variants/carousel-rtl"),
  "carousel-size": () => import("./variants/carousel-size"),
  "carousel-spacing": () => import("./variants/carousel-spacing"),
  "chart-demo": () => import("./variants/chart-demo"),
  "chart-example": () => import("./variants/chart-example"),
  "chart-example-axis": () => import("./variants/chart-example-axis"),
  "chart-example-grid": () => import("./variants/chart-example-grid"),
  "chart-example-legend": () => import("./variants/chart-example-legend"),
  "chart-example-tooltip": () => import("./variants/chart-example-tooltip"),
  "chart-rtl": () => import("./variants/chart-rtl"),
  "chart-tooltip": () => import("./variants/chart-tooltip"),
  "checkbox-basic": () => import("./variants/checkbox-basic"),
  "checkbox-demo": () => import("./variants/checkbox-demo"),
  "checkbox-description": () => import("./variants/checkbox-description"),
  "checkbox-disabled": () => import("./variants/checkbox-disabled"),
  "checkbox-group": () => import("./variants/checkbox-group"),
  "checkbox-invalid": () => import("./variants/checkbox-invalid"),
  "checkbox-rtl": () => import("./variants/checkbox-rtl"),
  "checkbox-table": () => import("./variants/checkbox-table"),
  "clipboard-text-demo": () => import("./variants/clipboard-text-demo"),
  "color-picker-demo": () => import("./variants/color-picker-demo"),
  "color-picker-alpha": () => import("./variants/color-picker-alpha"),
  "color-picker-swatches": () => import("./variants/color-picker-swatches"),
  "clipboard-text-display-value": () =>
    import("./variants/clipboard-text-display-value"),
  "clipboard-text-feedback": () => import("./variants/clipboard-text-feedback"),
  "collapsible-basic": () => import("./variants/collapsible-basic"),
  "collapsible-demo": () => import("./variants/collapsible-demo"),
  "collapsible-file-tree": () => import("./variants/collapsible-file-tree"),
  "collapsible-rtl": () => import("./variants/collapsible-rtl"),
  "collapsible-settings": () => import("./variants/collapsible-settings"),
  "combobox-auto-highlight": () => import("./variants/combobox-auto-highlight"),
  "combobox-basic": () => import("./variants/combobox-basic"),
  "combobox-clear": () => import("./variants/combobox-clear"),
  "combobox-custom": () => import("./variants/combobox-custom"),
  "combobox-demo": () => import("./variants/combobox-demo"),
  "combobox-disabled": () => import("./variants/combobox-disabled"),
  "combobox-groups": () => import("./variants/combobox-groups"),
  "combobox-input-group": () => import("./variants/combobox-input-group"),
  "combobox-invalid": () => import("./variants/combobox-invalid"),
  "combobox-multiple": () => import("./variants/combobox-multiple"),
  "combobox-popup": () => import("./variants/combobox-popup"),
  "combobox-rtl": () => import("./variants/combobox-rtl"),
  "command-basic": () => import("./variants/command-basic"),
  "command-demo": () => import("./variants/command-demo"),
  "command-groups": () => import("./variants/command-groups"),
  "command-rtl": () => import("./variants/command-rtl"),
  "command-scrollable": () => import("./variants/command-scrollable"),
  "command-shortcuts": () => import("./variants/command-shortcuts"),
  "context-menu-basic": () => import("./variants/context-menu-basic"),
  "context-menu-checkboxes": () => import("./variants/context-menu-checkboxes"),
  "context-menu-demo": () => import("./variants/context-menu-demo"),
  "context-menu-destructive": () =>
    import("./variants/context-menu-destructive"),
  "context-menu-groups": () => import("./variants/context-menu-groups"),
  "context-menu-icons": () => import("./variants/context-menu-icons"),
  "context-menu-radio": () => import("./variants/context-menu-radio"),
  "context-menu-rtl": () => import("./variants/context-menu-rtl"),
  "context-menu-shortcuts": () => import("./variants/context-menu-shortcuts"),
  "context-menu-sides": () => import("./variants/context-menu-sides"),
  "context-menu-submenu": () => import("./variants/context-menu-submenu"),
  "design-guidelines-collapse-content-size": () =>
    import("./variants/design-guidelines-collapse-content-size"),
  "design-guidelines-concentric-border-radius": () =>
    import("./variants/design-guidelines-concentric-border-radius"),
  "design-guidelines-content-text-size": () =>
    import("./variants/design-guidelines-content-text-size"),
  "design-guidelines-dialog-rendering": () =>
    import("./variants/design-guidelines-dialog-rendering"),
  "design-guidelines-font-tracking": () =>
    import("./variants/design-guidelines-font-tracking"),
  "design-guidelines-font-weight": () =>
    import("./variants/design-guidelines-font-weight"),
  "design-guidelines-heading-case": () =>
    import("./variants/design-guidelines-heading-case"),
  "design-guidelines-hover-color-transitions": () =>
    import("./variants/design-guidelines-hover-color-transitions"),
  "design-guidelines-icon-alignment": () =>
    import("./variants/design-guidelines-icon-alignment"),
  "design-guidelines-inline-monospace-size": () =>
    import("./variants/design-guidelines-inline-monospace-size"),
  "design-guidelines-layer-card-nesting": () =>
    import("./variants/design-guidelines-layer-card-nesting"),
  "design-guidelines-related-text-spacing": () =>
    import("./variants/design-guidelines-related-text-spacing"),
  "design-guidelines-shadow-borders": () =>
    import("./variants/design-guidelines-shadow-borders"),
  "design-guidelines-sticky-borders": () =>
    import("./variants/design-guidelines-sticky-borders"),
  "design-guidelines-text-spacing": () =>
    import("./variants/design-guidelines-text-spacing"),
  "dialog-close-button": () => import("./variants/dialog-close-button"),
  "dialog-demo": () => import("./variants/dialog-demo"),
  "dialog-no-close-button": () => import("./variants/dialog-no-close-button"),
  "dialog-rtl": () => import("./variants/dialog-rtl"),
  "dialog-scrollable-content": () =>
    import("./variants/dialog-scrollable-content"),
  "dialog-sticky-footer": () => import("./variants/dialog-sticky-footer"),
  "drawer-demo": () => import("./variants/drawer-demo"),
  "drawer-dialog": () => import("./variants/drawer-dialog"),
  "drawer-nested": () => import("./variants/drawer-nested"),
  "drawer-non-modal": () => import("./variants/drawer-non-modal"),
  "drawer-sides": () => import("./variants/drawer-sides"),
  "drawer-snap-points": () => import("./variants/drawer-snap-points"),
  "drawer-swipe-handle": () => import("./variants/drawer-swipe-handle"),
  "dropdown-menu-avatar": () => import("./variants/dropdown-menu-avatar"),
  "dropdown-menu-basic": () => import("./variants/dropdown-menu-basic"),
  "dropdown-menu-checkboxes": () =>
    import("./variants/dropdown-menu-checkboxes"),
  "dropdown-menu-checkboxes-icons": () =>
    import("./variants/dropdown-menu-checkboxes-icons"),
  "dropdown-menu-complex": () => import("./variants/dropdown-menu-complex"),
  "dropdown-menu-demo": () => import("./variants/dropdown-menu-demo"),
  "dropdown-menu-destructive": () =>
    import("./variants/dropdown-menu-destructive"),
  "dropdown-menu-icons": () => import("./variants/dropdown-menu-icons"),
  "dropdown-menu-radio-group": () =>
    import("./variants/dropdown-menu-radio-group"),
  "dropdown-menu-radio-icons": () =>
    import("./variants/dropdown-menu-radio-icons"),
  "dropdown-menu-rtl": () => import("./variants/dropdown-menu-rtl"),
  "dropdown-menu-shortcuts": () => import("./variants/dropdown-menu-shortcuts"),
  "dropdown-menu-submenu": () => import("./variants/dropdown-menu-submenu"),
  "empty-avatar": () => import("./variants/empty-avatar"),
  "empty-avatar-group": () => import("./variants/empty-avatar-group"),
  "empty-background": () => import("./variants/empty-background"),
  "empty-demo": () => import("./variants/empty-demo"),
  "empty-input-group": () => import("./variants/empty-input-group"),
  "empty-outline": () => import("./variants/empty-outline"),
  "empty-rtl": () => import("./variants/empty-rtl"),
  "field-checkbox": () => import("./variants/field-checkbox"),
  "field-choice-card": () => import("./variants/field-choice-card"),
  "field-demo": () => import("./variants/field-demo"),
  "field-fieldset": () => import("./variants/field-fieldset"),
  "field-group": () => import("./variants/field-group"),
  "field-input": () => import("./variants/field-input"),
  "field-radio": () => import("./variants/field-radio"),
  "field-responsive": () => import("./variants/field-responsive"),
  "field-rtl": () => import("./variants/field-rtl"),
  "field-select": () => import("./variants/field-select"),
  "field-slider": () => import("./variants/field-slider"),
  "field-switch": () => import("./variants/field-switch"),
  "field-textarea": () => import("./variants/field-textarea"),
  "hover-card-demo": () => import("./variants/hover-card-demo"),
  "hover-card-rtl": () => import("./variants/hover-card-rtl"),
  "hover-card-sides": () => import("./variants/hover-card-sides"),
  "inline-copy-text-custom-value": () =>
    import("./variants/inline-copy-text-custom-value"),
  "inline-copy-text-demo": () => import("./variants/inline-copy-text-demo"),
  "inline-copy-text-disabled": () =>
    import("./variants/inline-copy-text-disabled"),
  "input-badge": () => import("./variants/input-badge"),
  "input-basic": () => import("./variants/input-basic"),
  "input-button-group": () => import("./variants/input-button-group"),
  "input-demo": () => import("./variants/input-demo"),
  "input-disabled": () => import("./variants/input-disabled"),
  "input-field": () => import("./variants/input-field"),
  "input-fieldgroup": () => import("./variants/input-fieldgroup"),
  "input-file": () => import("./variants/input-file"),
  "input-form": () => import("./variants/input-form"),
  "input-grid": () => import("./variants/input-grid"),
  "input-group-block-end": () => import("./variants/input-group-block-end"),
  "input-group-block-start": () => import("./variants/input-group-block-start"),
  "input-group-button": () => import("./variants/input-group-button"),
  "input-group-custom": () => import("./variants/input-group-custom"),
  "input-group-demo": () => import("./variants/input-group-demo"),
  "input-group-dropdown": () => import("./variants/input-group-dropdown"),
  "input-group-icon": () => import("./variants/input-group-icon"),
  "input-group-inline-end": () => import("./variants/input-group-inline-end"),
  "input-group-inline-start": () =>
    import("./variants/input-group-inline-start"),
  "input-group-kbd": () => import("./variants/input-group-kbd"),
  "input-group-loading": () => import("./variants/input-group-loading"),
  "input-group-rtl": () => import("./variants/input-group-rtl"),
  "input-group-text": () => import("./variants/input-group-text"),
  "input-group-textarea": () => import("./variants/input-group-textarea"),
  "input-inline": () => import("./variants/input-inline"),
  "input-input-group": () => import("./variants/input-input-group"),
  "input-invalid": () => import("./variants/input-invalid"),
  "input-otp-alphanumeric": () => import("./variants/input-otp-alphanumeric"),
  "input-otp-controlled": () => import("./variants/input-otp-controlled"),
  "input-otp-demo": () => import("./variants/input-otp-demo"),
  "input-otp-disabled": () => import("./variants/input-otp-disabled"),
  "input-otp-form": () => import("./variants/input-otp-form"),
  "input-otp-four-digits": () => import("./variants/input-otp-four-digits"),
  "input-otp-invalid": () => import("./variants/input-otp-invalid"),
  "input-otp-masked": () => import("./variants/input-otp-masked"),
  "input-otp-pattern": () => import("./variants/input-otp-pattern"),
  "input-otp-rtl": () => import("./variants/input-otp-rtl"),
  "input-otp-separator": () => import("./variants/input-otp-separator"),
  "input-required": () => import("./variants/input-required"),
  "input-rtl": () => import("./variants/input-rtl"),
  "item-avatar": () => import("./variants/item-avatar"),
  "item-demo": () => import("./variants/item-demo"),
  "item-dropdown": () => import("./variants/item-dropdown"),
  "item-group": () => import("./variants/item-group"),
  "item-header": () => import("./variants/item-header"),
  "item-icon": () => import("./variants/item-icon"),
  "item-image": () => import("./variants/item-image"),
  "item-link": () => import("./variants/item-link"),
  "item-rtl": () => import("./variants/item-rtl"),
  "item-size": () => import("./variants/item-size"),
  "item-variant": () => import("./variants/item-variant"),
  "kbd-button": () => import("./variants/kbd-button"),
  "kbd-demo": () => import("./variants/kbd-demo"),
  "kbd-group": () => import("./variants/kbd-group"),
  "kbd-input-group": () => import("./variants/kbd-input-group"),
  "kbd-rtl": () => import("./variants/kbd-rtl"),
  "kbd-tooltip": () => import("./variants/kbd-tooltip"),
  "label-demo": () => import("./variants/label-demo"),
  "label-rtl": () => import("./variants/label-rtl"),
  "loader-button": () => import("./variants/loader-button"),
  "loader-demo": () => import("./variants/loader-demo"),
  "loader-size": () => import("./variants/loader-size"),
  "marker-border": () => import("./variants/marker-border"),
  "marker-demo": () => import("./variants/marker-demo"),
  "marker-icon": () => import("./variants/marker-icon"),
  "marker-link-button": () => import("./variants/marker-link-button"),
  "marker-separator": () => import("./variants/marker-separator"),
  "marker-shimmer": () => import("./variants/marker-shimmer"),
  "marker-status": () => import("./variants/marker-status"),
  "marker-variants": () => import("./variants/marker-variants"),
  "menubar-checkbox": () => import("./variants/menubar-checkbox"),
  "menubar-demo": () => import("./variants/menubar-demo"),
  "menubar-icons": () => import("./variants/menubar-icons"),
  "menubar-radio": () => import("./variants/menubar-radio"),
  "menubar-rtl": () => import("./variants/menubar-rtl"),
  "menubar-submenu": () => import("./variants/menubar-submenu"),
  "message-actions": () => import("./variants/message-actions"),
  "message-attachment": () => import("./variants/message-attachment"),
  "message-avatar": () => import("./variants/message-avatar"),
  "message-demo": () => import("./variants/message-demo"),
  "message-group": () => import("./variants/message-group"),
  "message-header-footer": () => import("./variants/message-header-footer"),
  "message-scroller-anchoring": () =>
    import("./variants/message-scroller-anchoring"),
  "message-scroller-animation": () =>
    import("./variants/message-scroller-animation"),
  "message-scroller-commands": () =>
    import("./variants/message-scroller-commands"),
  "message-scroller-demo": () => import("./variants/message-scroller-demo"),
  "message-scroller-group-chat": () =>
    import("./variants/message-scroller-group-chat"),
  "message-scroller-load-history": () =>
    import("./variants/message-scroller-load-history"),
  "message-scroller-opening-position": () =>
    import("./variants/message-scroller-opening-position"),
  "message-scroller-previous-context": () =>
    import("./variants/message-scroller-previous-context"),
  "message-scroller-scrollable": () =>
    import("./variants/message-scroller-scrollable"),
  "message-scroller-streaming": () =>
    import("./variants/message-scroller-streaming"),
  "message-scroller-visibility": () =>
    import("./variants/message-scroller-visibility"),
  "native-select-demo": () => import("./variants/native-select-demo"),
  "native-select-disabled": () => import("./variants/native-select-disabled"),
  "native-select-groups": () => import("./variants/native-select-groups"),
  "native-select-invalid": () => import("./variants/native-select-invalid"),
  "native-select-rtl": () => import("./variants/native-select-rtl"),
  "navigation-menu-demo": () => import("./variants/navigation-menu-demo"),
  "navigation-menu-rtl": () => import("./variants/navigation-menu-rtl"),
  "pagination-custom": () => import("./variants/pagination-custom"),
  "pagination-demo": () => import("./variants/pagination-demo"),
  "pagination-dropdown": () => import("./variants/pagination-dropdown"),
  "pagination-icons-only": () => import("./variants/pagination-icons-only"),
  "pagination-links": () => import("./variants/pagination-links"),
  "pagination-rtl": () => import("./variants/pagination-rtl"),
  "pagination-simple": () => import("./variants/pagination-simple"),
  "pagination-states": () => import("./variants/pagination-states"),
  "pagination-unknown-total": () =>
    import("./variants/pagination-unknown-total"),
  "popover-alignments": () => import("./variants/popover-alignments"),
  "popover-basic": () => import("./variants/popover-basic"),
  "popover-demo": () => import("./variants/popover-demo"),
  "popover-form": () => import("./variants/popover-form"),
  "popover-rtl": () => import("./variants/popover-rtl"),
  "progress-controlled": () => import("./variants/progress-controlled"),
  "progress-demo": () => import("./variants/progress-demo"),
  "progress-label": () => import("./variants/progress-label"),
  "progress-rtl": () => import("./variants/progress-rtl"),
  "questionnaire-animated": () => import("./variants/questionnaire-animated"),
  "questionnaire-card": () => import("./variants/questionnaire-card"),
  "questionnaire-conditional": () =>
    import("./variants/questionnaire-conditional"),
  "questionnaire-controlled": () =>
    import("./variants/questionnaire-controlled"),
  "questionnaire-demo": () => import("./variants/questionnaire-demo"),
  "questionnaire-dialog": () => import("./variants/questionnaire-dialog"),
  "questionnaire-freeform": () => import("./variants/questionnaire-freeform"),
  "questionnaire-multiple": () => import("./variants/questionnaire-multiple"),
  "questionnaire-navigation-state": () =>
    import("./variants/questionnaire-navigation-state"),
  "questionnaire-progress": () => import("./variants/questionnaire-progress"),
  "questionnaire-resume": () => import("./variants/questionnaire-resume"),
  "questionnaire-shortcuts": () => import("./variants/questionnaire-shortcuts"),
  "questionnaire-skip": () => import("./variants/questionnaire-skip"),
  "questionnaire-validation": () =>
    import("./variants/questionnaire-validation"),
  "radio-group-choice-card": () => import("./variants/radio-group-choice-card"),
  "radio-group-demo": () => import("./variants/radio-group-demo"),
  "radio-group-description": () => import("./variants/radio-group-description"),
  "radio-group-disabled": () => import("./variants/radio-group-disabled"),
  "radio-group-fieldset": () => import("./variants/radio-group-fieldset"),
  "radio-group-invalid": () => import("./variants/radio-group-invalid"),
  "radio-group-rtl": () => import("./variants/radio-group-rtl"),
  "resizable-demo": () => import("./variants/resizable-demo"),
  "resizable-handle": () => import("./variants/resizable-handle"),
  "resizable-rtl": () => import("./variants/resizable-rtl"),
  "resizable-vertical": () => import("./variants/resizable-vertical"),
  "scroll-area-demo": () => import("./variants/scroll-area-demo"),
  "scroll-area-horizontal-demo": () =>
    import("./variants/scroll-area-horizontal-demo"),
  "scroll-area-rtl": () => import("./variants/scroll-area-rtl"),
  "scroll-fade-demo": () => import("./variants/scroll-fade-demo"),
  "scroll-fade-edge": () => import("./variants/scroll-fade-edge"),
  "scroll-fade-horizontal": () => import("./variants/scroll-fade-horizontal"),
  "scroll-fade-none": () => import("./variants/scroll-fade-none"),
  "scroll-fade-overflow": () => import("./variants/scroll-fade-overflow"),
  "scroll-fade-rtl": () => import("./variants/scroll-fade-rtl"),
  "scroll-fade-size": () => import("./variants/scroll-fade-size"),
  "select-align-item": () => import("./variants/select-align-item"),
  "select-demo": () => import("./variants/select-demo"),
  "select-disabled": () => import("./variants/select-disabled"),
  "select-groups": () => import("./variants/select-groups"),
  "select-invalid": () => import("./variants/select-invalid"),
  "select-rtl": () => import("./variants/select-rtl"),
  "select-scrollable": () => import("./variants/select-scrollable"),
  "sensitive-input-controlled": () =>
    import("./variants/sensitive-input-controlled"),
  "sensitive-input-demo": () => import("./variants/sensitive-input-demo"),
  "sensitive-input-states": () => import("./variants/sensitive-input-states"),
  "separator-demo": () => import("./variants/separator-demo"),
  "separator-list": () => import("./variants/separator-list"),
  "separator-menu": () => import("./variants/separator-menu"),
  "separator-rtl": () => import("./variants/separator-rtl"),
  "separator-vertical": () => import("./variants/separator-vertical"),
  "sheet-demo": () => import("./variants/sheet-demo"),
  "sheet-no-close-button": () => import("./variants/sheet-no-close-button"),
  "sheet-rtl": () => import("./variants/sheet-rtl"),
  "sheet-side": () => import("./variants/sheet-side"),
  "shimmer-angle": () => import("./variants/shimmer-angle"),
  "shimmer-color": () => import("./variants/shimmer-color"),
  "shimmer-demo": () => import("./variants/shimmer-demo"),
  "shimmer-duration": () => import("./variants/shimmer-duration"),
  "shimmer-marker": () => import("./variants/shimmer-marker"),
  "shimmer-none": () => import("./variants/shimmer-none"),
  "shimmer-once": () => import("./variants/shimmer-once"),
  "shimmer-rtl": () => import("./variants/shimmer-rtl"),
  "shimmer-spread": () => import("./variants/shimmer-spread"),
  "sidebar-demo": () => import("./variants/sidebar-demo"),
  "skeleton-avatar": () => import("./variants/skeleton-avatar"),
  "skeleton-card": () => import("./variants/skeleton-card"),
  "skeleton-demo": () => import("./variants/skeleton-demo"),
  "skeleton-form": () => import("./variants/skeleton-form"),
  "skeleton-rtl": () => import("./variants/skeleton-rtl"),
  "skeleton-table": () => import("./variants/skeleton-table"),
  "skeleton-text": () => import("./variants/skeleton-text"),
  "slider-controlled": () => import("./variants/slider-controlled"),
  "slider-demo": () => import("./variants/slider-demo"),
  "slider-disabled": () => import("./variants/slider-disabled"),
  "slider-multiple": () => import("./variants/slider-multiple"),
  "slider-range": () => import("./variants/slider-range"),
  "slider-rtl": () => import("./variants/slider-rtl"),
  "slider-vertical": () => import("./variants/slider-vertical"),
  "switch-choice-card": () => import("./variants/switch-choice-card"),
  "switch-demo": () => import("./variants/switch-demo"),
  "switch-description": () => import("./variants/switch-description"),
  "switch-disabled": () => import("./variants/switch-disabled"),
  "switch-invalid": () => import("./variants/switch-invalid"),
  "switch-rtl": () => import("./variants/switch-rtl"),
  "switch-sizes": () => import("./variants/switch-sizes"),
  "table-actions": () => import("./variants/table-actions"),
  "tab-bar-demo": () => import("./variants/tab-bar-demo"),
  "table-demo": () => import("./variants/table-demo"),
  "table-footer": () => import("./variants/table-footer"),
  "table-rtl": () => import("./variants/table-rtl"),
  "tabs-demo": () => import("./variants/tabs-demo"),
  "tabs-disabled": () => import("./variants/tabs-disabled"),
  "tabs-icons": () => import("./variants/tabs-icons"),
  "tabs-line": () => import("./variants/tabs-line"),
  "tabs-overflow": () => import("./variants/tabs-overflow"),
  "tabs-rtl": () => import("./variants/tabs-rtl"),
  "tabs-segment": () => import("./variants/tabs-segment"),
  "tabs-vertical": () => import("./variants/tabs-vertical"),
  "tag-input-demo": () => import("./variants/tag-input-demo"),
  "tag-input-form": () => import("./variants/tag-input-form"),
  "tag-input-suggestions": () => import("./variants/tag-input-suggestions"),
  "tag-input-validation": () => import("./variants/tag-input-validation"),
  "textarea-button": () => import("./variants/textarea-button"),
  "textarea-demo": () => import("./variants/textarea-demo"),
  "textarea-disabled": () => import("./variants/textarea-disabled"),
  "textarea-field": () => import("./variants/textarea-field"),
  "textarea-invalid": () => import("./variants/textarea-invalid"),
  "textarea-rtl": () => import("./variants/textarea-rtl"),
  "theming-mode-comparison": () => import("./variants/theming-mode-comparison"),
  "theming-palette-playground": () =>
    import("./variants/theming-palette-playground"),
  "theming-custom-color": () => import("./variants/theming-custom-color"),
  "theming-semantic-colors": () => import("./variants/theming-semantic-colors"),
  "toast-demo": () => import("./variants/toast-demo"),
  "toast-promise": () => import("./variants/toast-promise"),
  "toast-types": () => import("./variants/toast-types"),
  "toggle-demo": () => import("./variants/toggle-demo"),
  "toggle-disabled": () => import("./variants/toggle-disabled"),
  "toggle-group-demo": () => import("./variants/toggle-group-demo"),
  "toggle-group-disabled": () => import("./variants/toggle-group-disabled"),
  "toggle-group-font-weight-selector": () =>
    import("./variants/toggle-group-font-weight-selector"),
  "toggle-group-outline": () => import("./variants/toggle-group-outline"),
  "toggle-group-rtl": () => import("./variants/toggle-group-rtl"),
  "toggle-group-sizes": () => import("./variants/toggle-group-sizes"),
  "toggle-group-spacing": () => import("./variants/toggle-group-spacing"),
  "toggle-group-vertical": () => import("./variants/toggle-group-vertical"),
  "toggle-outline": () => import("./variants/toggle-outline"),
  "toggle-rtl": () => import("./variants/toggle-rtl"),
  "toggle-sizes": () => import("./variants/toggle-sizes"),
  "toggle-text": () => import("./variants/toggle-text"),
  "toolbar-demo": () => import("./variants/toolbar-demo"),
  "toolbar-disabled": () => import("./variants/toolbar-disabled"),
  "toolbar-search": () => import("./variants/toolbar-search"),
  "tooltip-demo": () => import("./variants/tooltip-demo"),
  "tooltip-disabled": () => import("./variants/tooltip-disabled"),
  "tooltip-keyboard": () => import("./variants/tooltip-keyboard"),
  "tooltip-rtl": () => import("./variants/tooltip-rtl"),
  "tooltip-sides": () => import("./variants/tooltip-sides"),
  "code-viewer-demo": () => import("./variants/code-viewer-demo"),
  "code-viewer-plain": () => import("./variants/code-viewer-plain"),
  "code-viewer-streaming": () => import("./variants/code-viewer-streaming"),
  "diff-viewer-demo": () => import("./variants/diff-viewer-demo"),
  "diff-viewer-streaming": () => import("./variants/diff-viewer-streaming"),
  "editor-demo": () => import("./variants/editor-demo"),
  "editor-preview": () => import("./variants/editor-preview"),
  "editor-toolbar": () => import("./variants/editor-toolbar"),
  "glass-composition": () => import("./variants/glass-composition"),
  "glass-demo": () => import("./variants/glass-demo"),
  "glass-dynamic": () => import("./variants/glass-dynamic"),
  "html-viewer-demo": () => import("./variants/html-viewer-demo"),
  "html-viewer-sandbox": () => import("./variants/html-viewer-sandbox"),
  "image-viewer-controlled": () => import("./variants/image-viewer-controlled"),
  "image-viewer-demo": () => import("./variants/image-viewer-demo"),
  "locale-toggle-demo": () => import("./variants/locale-toggle-demo"),
  "locale-toggle-select": () => import("./variants/locale-toggle-select"),
  "markdown-viewer-demo": () => import("./variants/markdown-viewer-demo"),
  "markdown-viewer-sanitized": () =>
    import("./variants/markdown-viewer-sanitized"),
  "qr-code-animated": () => import("./variants/qr-code-animated"),
  "qr-code-demo": () => import("./variants/qr-code-demo"),
  "qr-code-glass": () => import("./variants/qr-code-glass.tsx"),
  "qr-code-margin": () => import("./variants/qr-code-margin.tsx"),
  "qr-code-logo": () => import("./variants/qr-code-logo"),
  "qr-code-states": () => import("./variants/qr-code-states"),
  "theme-toggle-demo": () => import("./variants/theme-toggle-demo"),
  "theme-toggle-variants": () => import("./variants/theme-toggle-variants"),
} satisfies Record<
  string,
  () => Promise<{ default: ComponentType<ExampleProps> }>
>;

export const sourceFiles = {
  "long-text-demo": () => import("./variants/long-text-demo.tsx?raw"),
  "long-text-table": () => import("./variants/long-text-table.tsx?raw"),
  "navigation-progress-demo": () =>
    import("./variants/navigation-progress-demo.tsx?raw"),
  "block-table-header": () => import("./variants/block-table-header.tsx?raw"),
  "block-table-search": () => import("./variants/block-table-search.tsx?raw"),
  "block-table-layout": () => import("./variants/block-table-layout.tsx?raw"),
  "block-table-demo": () => import("./variants/block-table-demo.tsx?raw"),
  "block-table-selection": () =>
    import("./variants/block-table-selection.tsx?raw"),
  "block-table-drag": () => import("./variants/block-table-drag.tsx?raw"),
  "block-table-request": () => import("./variants/block-table-request.tsx?raw"),
  "block-table-states": () => import("./variants/block-table-states.tsx?raw"),
  "block-form-report": () => import("./variants/block-form-report.tsx?raw"),
  "block-form-profile": () => import("./variants/block-form-profile.tsx?raw"),
  "block-delete-resource": () =>
    import("./variants/block-delete-resource.tsx?raw"),
  "block-delete-resource-error": () =>
    import("./variants/block-delete-resource-error.tsx?raw"),
  "block-delete-resource-insensitive": () =>
    import("./variants/block-delete-resource-insensitive.tsx?raw"),
  "accordion-basic": () => import("./variants/accordion-basic.tsx?raw"),
  "accordion-borders": () => import("./variants/accordion-borders.tsx?raw"),
  "accordion-card": () => import("./variants/accordion-card.tsx?raw"),
  "accordion-demo": () => import("./variants/accordion-demo.tsx?raw"),
  "accordion-disabled": () => import("./variants/accordion-disabled.tsx?raw"),
  "accordion-multiple": () => import("./variants/accordion-multiple.tsx?raw"),
  "accordion-rtl": () => import("./variants/accordion-rtl.tsx?raw"),
  "alert-action": () => import("./variants/alert-action.tsx?raw"),
  "alert-basic": () => import("./variants/alert-basic.tsx?raw"),
  "alert-colors": () => import("./variants/alert-colors.tsx?raw"),
  "alert-demo": () => import("./variants/alert-demo.tsx?raw"),
  "alert-destructive": () => import("./variants/alert-destructive.tsx?raw"),
  "alert-dialog-basic": () => import("./variants/alert-dialog-basic.tsx?raw"),
  "alert-dialog-demo": () => import("./variants/alert-dialog-demo.tsx?raw"),
  "alert-dialog-destructive": () =>
    import("./variants/alert-dialog-destructive.tsx?raw"),
  "alert-dialog-media": () => import("./variants/alert-dialog-media.tsx?raw"),
  "alert-dialog-rtl": () => import("./variants/alert-dialog-rtl.tsx?raw"),
  "alert-dialog-small": () => import("./variants/alert-dialog-small.tsx?raw"),
  "alert-dialog-small-media": () =>
    import("./variants/alert-dialog-small-media.tsx?raw"),
  "alert-rtl": () => import("./variants/alert-rtl.tsx?raw"),
  "aspect-ratio-demo": () => import("./variants/aspect-ratio-demo.tsx?raw"),
  "aspect-ratio-portrait": () =>
    import("./variants/aspect-ratio-portrait.tsx?raw"),
  "aspect-ratio-rtl": () => import("./variants/aspect-ratio-rtl.tsx?raw"),
  "aspect-ratio-square": () => import("./variants/aspect-ratio-square.tsx?raw"),
  "attachment-demo": () => import("./variants/attachment-demo.tsx?raw"),
  "attachment-group": () => import("./variants/attachment-group.tsx?raw"),
  "attachment-image": () => import("./variants/attachment-image.tsx?raw"),
  "attachment-sizes": () => import("./variants/attachment-sizes.tsx?raw"),
  "attachment-states": () => import("./variants/attachment-states.tsx?raw"),
  "attachment-trigger": () => import("./variants/attachment-trigger.tsx?raw"),
  "autocomplete-demo": () => import("./variants/autocomplete-demo.tsx?raw"),
  "autocomplete-disabled": () =>
    import("./variants/autocomplete-disabled.tsx?raw"),
  "autocomplete-grouped": () =>
    import("./variants/autocomplete-grouped.tsx?raw"),
  "avatar-badge": () => import("./variants/avatar-badge.tsx?raw"),
  "avatar-badge-icon": () => import("./variants/avatar-badge-icon.tsx?raw"),
  "avatar-basic": () => import("./variants/avatar-basic.tsx?raw"),
  "avatar-demo": () => import("./variants/avatar-demo.tsx?raw"),
  "avatar-dropdown": () => import("./variants/avatar-dropdown.tsx?raw"),
  "avatar-group": () => import("./variants/avatar-group.tsx?raw"),
  "avatar-group-count": () => import("./variants/avatar-group-count.tsx?raw"),
  "avatar-group-count-icon": () =>
    import("./variants/avatar-group-count-icon.tsx?raw"),
  "avatar-rtl": () => import("./variants/avatar-rtl.tsx?raw"),
  "avatar-size": () => import("./variants/avatar-size.tsx?raw"),
  "badge-colors": () => import("./variants/badge-colors.tsx?raw"),
  "badge-demo": () => import("./variants/badge-demo.tsx?raw"),
  "badge-icon": () => import("./variants/badge-icon.tsx?raw"),
  "badge-link": () => import("./variants/badge-link.tsx?raw"),
  "badge-loading": () => import("./variants/badge-loading.tsx?raw"),
  "badge-rtl": () => import("./variants/badge-rtl.tsx?raw"),
  "badge-variants": () => import("./variants/badge-variants.tsx?raw"),
  "breadcrumb-basic": () => import("./variants/breadcrumb-basic.tsx?raw"),
  "breadcrumb-demo": () => import("./variants/breadcrumb-demo.tsx?raw"),
  "breadcrumb-dropdown": () => import("./variants/breadcrumb-dropdown.tsx?raw"),
  "breadcrumb-ellipsis": () => import("./variants/breadcrumb-ellipsis.tsx?raw"),
  "breadcrumb-link": () => import("./variants/breadcrumb-link.tsx?raw"),
  "breadcrumb-rtl": () => import("./variants/breadcrumb-rtl.tsx?raw"),
  "breadcrumb-separator": () =>
    import("./variants/breadcrumb-separator.tsx?raw"),
  "bubble-alignment": () => import("./variants/bubble-alignment.tsx?raw"),
  "bubble-collapsible": () => import("./variants/bubble-collapsible.tsx?raw"),
  "bubble-demo": () => import("./variants/bubble-demo.tsx?raw"),
  "bubble-group-demo": () => import("./variants/bubble-group-demo.tsx?raw"),
  "bubble-link-button": () => import("./variants/bubble-link-button.tsx?raw"),
  "bubble-popover": () => import("./variants/bubble-popover.tsx?raw"),
  "bubble-reactions": () => import("./variants/bubble-reactions.tsx?raw"),
  "bubble-tooltip": () => import("./variants/bubble-tooltip.tsx?raw"),
  "bubble-variants": () => import("./variants/bubble-variants.tsx?raw"),
  "button-default": () => import("./variants/button-default.tsx?raw"),
  "button-demo": () => import("./variants/button-demo.tsx?raw"),
  "button-destructive": () => import("./variants/button-destructive.tsx?raw"),
  "button-ghost": () => import("./variants/button-ghost.tsx?raw"),
  "button-group-demo": () => import("./variants/button-group-demo.tsx?raw"),
  "button-group-dropdown": () =>
    import("./variants/button-group-dropdown.tsx?raw"),
  "button-group-input": () => import("./variants/button-group-input.tsx?raw"),
  "button-group-input-group": () =>
    import("./variants/button-group-input-group.tsx?raw"),
  "button-group-nested": () => import("./variants/button-group-nested.tsx?raw"),
  "button-group-orientation": () =>
    import("./variants/button-group-orientation.tsx?raw"),
  "button-group-popover": () =>
    import("./variants/button-group-popover.tsx?raw"),
  "button-group-rtl": () => import("./variants/button-group-rtl.tsx?raw"),
  "button-group-select": () => import("./variants/button-group-select.tsx?raw"),
  "button-group-separator": () =>
    import("./variants/button-group-separator.tsx?raw"),
  "button-group-size": () => import("./variants/button-group-size.tsx?raw"),
  "button-group-split": () => import("./variants/button-group-split.tsx?raw"),
  "button-icon": () => import("./variants/button-icon.tsx?raw"),
  "button-link": () => import("./variants/button-link.tsx?raw"),
  "button-loading": () => import("./variants/button-loading.tsx?raw"),
  "button-outline": () => import("./variants/button-outline.tsx?raw"),
  "button-render": () => import("./variants/button-render.tsx?raw"),
  "button-rounded": () => import("./variants/button-rounded.tsx?raw"),
  "button-rtl": () => import("./variants/button-rtl.tsx?raw"),
  "button-secondary": () => import("./variants/button-secondary.tsx?raw"),
  "button-size": () => import("./variants/button-size.tsx?raw"),
  "button-with-icon": () => import("./variants/button-with-icon.tsx?raw"),
  "calendar-basic": () => import("./variants/calendar-basic.tsx?raw"),
  "calendar-booked-dates": () =>
    import("./variants/calendar-booked-dates.tsx?raw"),
  "calendar-caption": () => import("./variants/calendar-caption.tsx?raw"),
  "calendar-custom-days": () =>
    import("./variants/calendar-custom-days.tsx?raw"),
  "calendar-demo": () => import("./variants/calendar-demo.tsx?raw"),
  "calendar-hijri": () => import("./variants/calendar-hijri.tsx?raw"),
  "calendar-presets": () => import("./variants/calendar-presets.tsx?raw"),
  "calendar-range": () => import("./variants/calendar-range.tsx?raw"),
  "calendar-rtl": () => import("./variants/calendar-rtl.tsx?raw"),
  "calendar-time": () => import("./variants/calendar-time.tsx?raw"),
  "calendar-week-numbers": () =>
    import("./variants/calendar-week-numbers.tsx?raw"),
  "card-demo": () => import("./variants/card-demo.tsx?raw"),
  "card-edge-to-edge": () => import("./variants/card-edge-to-edge.tsx?raw"),
  "card-image": () => import("./variants/card-image.tsx?raw"),
  "card-rtl": () => import("./variants/card-rtl.tsx?raw"),
  "card-small": () => import("./variants/card-small.tsx?raw"),
  "card-spacing": () => import("./variants/card-spacing.tsx?raw"),
  "carousel-api": () => import("./variants/carousel-api.tsx?raw"),
  "carousel-demo": () => import("./variants/carousel-demo.tsx?raw"),
  "carousel-orientation": () =>
    import("./variants/carousel-orientation.tsx?raw"),
  "carousel-plugin": () => import("./variants/carousel-plugin.tsx?raw"),
  "carousel-rtl": () => import("./variants/carousel-rtl.tsx?raw"),
  "carousel-size": () => import("./variants/carousel-size.tsx?raw"),
  "carousel-spacing": () => import("./variants/carousel-spacing.tsx?raw"),
  "chart-demo": () => import("./variants/chart-demo.tsx?raw"),
  "chart-example": () => import("./variants/chart-example.tsx?raw"),
  "chart-example-axis": () => import("./variants/chart-example-axis.tsx?raw"),
  "chart-example-grid": () => import("./variants/chart-example-grid.tsx?raw"),
  "chart-example-legend": () =>
    import("./variants/chart-example-legend.tsx?raw"),
  "chart-example-tooltip": () =>
    import("./variants/chart-example-tooltip.tsx?raw"),
  "chart-rtl": () => import("./variants/chart-rtl.tsx?raw"),
  "chart-tooltip": () => import("./variants/chart-tooltip.tsx?raw"),
  "checkbox-basic": () => import("./variants/checkbox-basic.tsx?raw"),
  "checkbox-demo": () => import("./variants/checkbox-demo.tsx?raw"),
  "checkbox-description": () =>
    import("./variants/checkbox-description.tsx?raw"),
  "checkbox-disabled": () => import("./variants/checkbox-disabled.tsx?raw"),
  "checkbox-group": () => import("./variants/checkbox-group.tsx?raw"),
  "checkbox-invalid": () => import("./variants/checkbox-invalid.tsx?raw"),
  "checkbox-rtl": () => import("./variants/checkbox-rtl.tsx?raw"),
  "checkbox-table": () => import("./variants/checkbox-table.tsx?raw"),
  "clipboard-text-demo": () => import("./variants/clipboard-text-demo.tsx?raw"),
  "color-picker-demo": () => import("./variants/color-picker-demo.tsx?raw"),
  "color-picker-alpha": () => import("./variants/color-picker-alpha.tsx?raw"),
  "color-picker-swatches": () =>
    import("./variants/color-picker-swatches.tsx?raw"),
  "clipboard-text-display-value": () =>
    import("./variants/clipboard-text-display-value.tsx?raw"),
  "clipboard-text-feedback": () =>
    import("./variants/clipboard-text-feedback.tsx?raw"),
  "collapsible-basic": () => import("./variants/collapsible-basic.tsx?raw"),
  "collapsible-demo": () => import("./variants/collapsible-demo.tsx?raw"),
  "collapsible-file-tree": () =>
    import("./variants/collapsible-file-tree.tsx?raw"),
  "collapsible-rtl": () => import("./variants/collapsible-rtl.tsx?raw"),
  "collapsible-settings": () =>
    import("./variants/collapsible-settings.tsx?raw"),
  "combobox-auto-highlight": () =>
    import("./variants/combobox-auto-highlight.tsx?raw"),
  "combobox-basic": () => import("./variants/combobox-basic.tsx?raw"),
  "combobox-clear": () => import("./variants/combobox-clear.tsx?raw"),
  "combobox-custom": () => import("./variants/combobox-custom.tsx?raw"),
  "combobox-demo": () => import("./variants/combobox-demo.tsx?raw"),
  "combobox-disabled": () => import("./variants/combobox-disabled.tsx?raw"),
  "combobox-groups": () => import("./variants/combobox-groups.tsx?raw"),
  "combobox-input-group": () =>
    import("./variants/combobox-input-group.tsx?raw"),
  "combobox-invalid": () => import("./variants/combobox-invalid.tsx?raw"),
  "combobox-multiple": () => import("./variants/combobox-multiple.tsx?raw"),
  "combobox-popup": () => import("./variants/combobox-popup.tsx?raw"),
  "combobox-rtl": () => import("./variants/combobox-rtl.tsx?raw"),
  "command-basic": () => import("./variants/command-basic.tsx?raw"),
  "command-demo": () => import("./variants/command-demo.tsx?raw"),
  "command-groups": () => import("./variants/command-groups.tsx?raw"),
  "command-rtl": () => import("./variants/command-rtl.tsx?raw"),
  "command-scrollable": () => import("./variants/command-scrollable.tsx?raw"),
  "command-shortcuts": () => import("./variants/command-shortcuts.tsx?raw"),
  "context-menu-basic": () => import("./variants/context-menu-basic.tsx?raw"),
  "context-menu-checkboxes": () =>
    import("./variants/context-menu-checkboxes.tsx?raw"),
  "context-menu-demo": () => import("./variants/context-menu-demo.tsx?raw"),
  "context-menu-destructive": () =>
    import("./variants/context-menu-destructive.tsx?raw"),
  "context-menu-groups": () => import("./variants/context-menu-groups.tsx?raw"),
  "context-menu-icons": () => import("./variants/context-menu-icons.tsx?raw"),
  "context-menu-radio": () => import("./variants/context-menu-radio.tsx?raw"),
  "context-menu-rtl": () => import("./variants/context-menu-rtl.tsx?raw"),
  "context-menu-shortcuts": () =>
    import("./variants/context-menu-shortcuts.tsx?raw"),
  "context-menu-sides": () => import("./variants/context-menu-sides.tsx?raw"),
  "context-menu-submenu": () =>
    import("./variants/context-menu-submenu.tsx?raw"),
  "design-guidelines-collapse-content-size": () =>
    import("./variants/design-guidelines-collapse-content-size.tsx?raw"),
  "design-guidelines-concentric-border-radius": () =>
    import("./variants/design-guidelines-concentric-border-radius.tsx?raw"),
  "design-guidelines-content-text-size": () =>
    import("./variants/design-guidelines-content-text-size.tsx?raw"),
  "design-guidelines-dialog-rendering": () =>
    import("./variants/design-guidelines-dialog-rendering.tsx?raw"),
  "design-guidelines-font-tracking": () =>
    import("./variants/design-guidelines-font-tracking.tsx?raw"),
  "design-guidelines-font-weight": () =>
    import("./variants/design-guidelines-font-weight.tsx?raw"),
  "design-guidelines-heading-case": () =>
    import("./variants/design-guidelines-heading-case.tsx?raw"),
  "design-guidelines-hover-color-transitions": () =>
    import("./variants/design-guidelines-hover-color-transitions.tsx?raw"),
  "design-guidelines-icon-alignment": () =>
    import("./variants/design-guidelines-icon-alignment.tsx?raw"),
  "design-guidelines-inline-monospace-size": () =>
    import("./variants/design-guidelines-inline-monospace-size.tsx?raw"),
  "design-guidelines-layer-card-nesting": () =>
    import("./variants/design-guidelines-layer-card-nesting.tsx?raw"),
  "design-guidelines-related-text-spacing": () =>
    import("./variants/design-guidelines-related-text-spacing.tsx?raw"),
  "design-guidelines-shadow-borders": () =>
    import("./variants/design-guidelines-shadow-borders.tsx?raw"),
  "design-guidelines-sticky-borders": () =>
    import("./variants/design-guidelines-sticky-borders.tsx?raw"),
  "design-guidelines-text-spacing": () =>
    import("./variants/design-guidelines-text-spacing.tsx?raw"),
  "dialog-close-button": () => import("./variants/dialog-close-button.tsx?raw"),
  "dialog-demo": () => import("./variants/dialog-demo.tsx?raw"),
  "dialog-no-close-button": () =>
    import("./variants/dialog-no-close-button.tsx?raw"),
  "dialog-rtl": () => import("./variants/dialog-rtl.tsx?raw"),
  "dialog-scrollable-content": () =>
    import("./variants/dialog-scrollable-content.tsx?raw"),
  "dialog-sticky-footer": () =>
    import("./variants/dialog-sticky-footer.tsx?raw"),
  "drawer-demo": () => import("./variants/drawer-demo.tsx?raw"),
  "drawer-dialog": () => import("./variants/drawer-dialog.tsx?raw"),
  "drawer-nested": () => import("./variants/drawer-nested.tsx?raw"),
  "drawer-non-modal": () => import("./variants/drawer-non-modal.tsx?raw"),
  "drawer-sides": () => import("./variants/drawer-sides.tsx?raw"),
  "drawer-snap-points": () => import("./variants/drawer-snap-points.tsx?raw"),
  "drawer-swipe-handle": () => import("./variants/drawer-swipe-handle.tsx?raw"),
  "dropdown-menu-avatar": () =>
    import("./variants/dropdown-menu-avatar.tsx?raw"),
  "dropdown-menu-basic": () => import("./variants/dropdown-menu-basic.tsx?raw"),
  "dropdown-menu-checkboxes": () =>
    import("./variants/dropdown-menu-checkboxes.tsx?raw"),
  "dropdown-menu-checkboxes-icons": () =>
    import("./variants/dropdown-menu-checkboxes-icons.tsx?raw"),
  "dropdown-menu-complex": () =>
    import("./variants/dropdown-menu-complex.tsx?raw"),
  "dropdown-menu-demo": () => import("./variants/dropdown-menu-demo.tsx?raw"),
  "dropdown-menu-destructive": () =>
    import("./variants/dropdown-menu-destructive.tsx?raw"),
  "dropdown-menu-icons": () => import("./variants/dropdown-menu-icons.tsx?raw"),
  "dropdown-menu-radio-group": () =>
    import("./variants/dropdown-menu-radio-group.tsx?raw"),
  "dropdown-menu-radio-icons": () =>
    import("./variants/dropdown-menu-radio-icons.tsx?raw"),
  "dropdown-menu-rtl": () => import("./variants/dropdown-menu-rtl.tsx?raw"),
  "dropdown-menu-shortcuts": () =>
    import("./variants/dropdown-menu-shortcuts.tsx?raw"),
  "dropdown-menu-submenu": () =>
    import("./variants/dropdown-menu-submenu.tsx?raw"),
  "empty-avatar": () => import("./variants/empty-avatar.tsx?raw"),
  "empty-avatar-group": () => import("./variants/empty-avatar-group.tsx?raw"),
  "empty-background": () => import("./variants/empty-background.tsx?raw"),
  "empty-demo": () => import("./variants/empty-demo.tsx?raw"),
  "empty-input-group": () => import("./variants/empty-input-group.tsx?raw"),
  "empty-outline": () => import("./variants/empty-outline.tsx?raw"),
  "empty-rtl": () => import("./variants/empty-rtl.tsx?raw"),
  "field-checkbox": () => import("./variants/field-checkbox.tsx?raw"),
  "field-choice-card": () => import("./variants/field-choice-card.tsx?raw"),
  "field-demo": () => import("./variants/field-demo.tsx?raw"),
  "field-fieldset": () => import("./variants/field-fieldset.tsx?raw"),
  "field-group": () => import("./variants/field-group.tsx?raw"),
  "field-input": () => import("./variants/field-input.tsx?raw"),
  "field-radio": () => import("./variants/field-radio.tsx?raw"),
  "field-responsive": () => import("./variants/field-responsive.tsx?raw"),
  "field-rtl": () => import("./variants/field-rtl.tsx?raw"),
  "field-select": () => import("./variants/field-select.tsx?raw"),
  "field-slider": () => import("./variants/field-slider.tsx?raw"),
  "field-switch": () => import("./variants/field-switch.tsx?raw"),
  "field-textarea": () => import("./variants/field-textarea.tsx?raw"),
  "hover-card-demo": () => import("./variants/hover-card-demo.tsx?raw"),
  "hover-card-rtl": () => import("./variants/hover-card-rtl.tsx?raw"),
  "hover-card-sides": () => import("./variants/hover-card-sides.tsx?raw"),
  "inline-copy-text-custom-value": () =>
    import("./variants/inline-copy-text-custom-value.tsx?raw"),
  "inline-copy-text-demo": () =>
    import("./variants/inline-copy-text-demo.tsx?raw"),
  "inline-copy-text-disabled": () =>
    import("./variants/inline-copy-text-disabled.tsx?raw"),
  "input-badge": () => import("./variants/input-badge.tsx?raw"),
  "input-basic": () => import("./variants/input-basic.tsx?raw"),
  "input-button-group": () => import("./variants/input-button-group.tsx?raw"),
  "input-demo": () => import("./variants/input-demo.tsx?raw"),
  "input-disabled": () => import("./variants/input-disabled.tsx?raw"),
  "input-field": () => import("./variants/input-field.tsx?raw"),
  "input-fieldgroup": () => import("./variants/input-fieldgroup.tsx?raw"),
  "input-file": () => import("./variants/input-file.tsx?raw"),
  "input-form": () => import("./variants/input-form.tsx?raw"),
  "input-grid": () => import("./variants/input-grid.tsx?raw"),
  "input-group-block-end": () =>
    import("./variants/input-group-block-end.tsx?raw"),
  "input-group-block-start": () =>
    import("./variants/input-group-block-start.tsx?raw"),
  "input-group-button": () => import("./variants/input-group-button.tsx?raw"),
  "input-group-custom": () => import("./variants/input-group-custom.tsx?raw"),
  "input-group-demo": () => import("./variants/input-group-demo.tsx?raw"),
  "input-group-dropdown": () =>
    import("./variants/input-group-dropdown.tsx?raw"),
  "input-group-icon": () => import("./variants/input-group-icon.tsx?raw"),
  "input-group-inline-end": () =>
    import("./variants/input-group-inline-end.tsx?raw"),
  "input-group-inline-start": () =>
    import("./variants/input-group-inline-start.tsx?raw"),
  "input-group-kbd": () => import("./variants/input-group-kbd.tsx?raw"),
  "input-group-loading": () => import("./variants/input-group-loading.tsx?raw"),
  "input-group-rtl": () => import("./variants/input-group-rtl.tsx?raw"),
  "input-group-text": () => import("./variants/input-group-text.tsx?raw"),
  "input-group-textarea": () =>
    import("./variants/input-group-textarea.tsx?raw"),
  "input-inline": () => import("./variants/input-inline.tsx?raw"),
  "input-input-group": () => import("./variants/input-input-group.tsx?raw"),
  "input-invalid": () => import("./variants/input-invalid.tsx?raw"),
  "input-otp-alphanumeric": () =>
    import("./variants/input-otp-alphanumeric.tsx?raw"),
  "input-otp-controlled": () =>
    import("./variants/input-otp-controlled.tsx?raw"),
  "input-otp-demo": () => import("./variants/input-otp-demo.tsx?raw"),
  "input-otp-disabled": () => import("./variants/input-otp-disabled.tsx?raw"),
  "input-otp-form": () => import("./variants/input-otp-form.tsx?raw"),
  "input-otp-four-digits": () =>
    import("./variants/input-otp-four-digits.tsx?raw"),
  "input-otp-invalid": () => import("./variants/input-otp-invalid.tsx?raw"),
  "input-otp-masked": () => import("./variants/input-otp-masked.tsx?raw"),
  "input-otp-pattern": () => import("./variants/input-otp-pattern.tsx?raw"),
  "input-otp-rtl": () => import("./variants/input-otp-rtl.tsx?raw"),
  "input-otp-separator": () => import("./variants/input-otp-separator.tsx?raw"),
  "input-required": () => import("./variants/input-required.tsx?raw"),
  "input-rtl": () => import("./variants/input-rtl.tsx?raw"),
  "item-avatar": () => import("./variants/item-avatar.tsx?raw"),
  "item-demo": () => import("./variants/item-demo.tsx?raw"),
  "item-dropdown": () => import("./variants/item-dropdown.tsx?raw"),
  "item-group": () => import("./variants/item-group.tsx?raw"),
  "item-header": () => import("./variants/item-header.tsx?raw"),
  "item-icon": () => import("./variants/item-icon.tsx?raw"),
  "item-image": () => import("./variants/item-image.tsx?raw"),
  "item-link": () => import("./variants/item-link.tsx?raw"),
  "item-rtl": () => import("./variants/item-rtl.tsx?raw"),
  "item-size": () => import("./variants/item-size.tsx?raw"),
  "item-variant": () => import("./variants/item-variant.tsx?raw"),
  "kbd-button": () => import("./variants/kbd-button.tsx?raw"),
  "kbd-demo": () => import("./variants/kbd-demo.tsx?raw"),
  "kbd-group": () => import("./variants/kbd-group.tsx?raw"),
  "kbd-input-group": () => import("./variants/kbd-input-group.tsx?raw"),
  "kbd-rtl": () => import("./variants/kbd-rtl.tsx?raw"),
  "kbd-tooltip": () => import("./variants/kbd-tooltip.tsx?raw"),
  "label-demo": () => import("./variants/label-demo.tsx?raw"),
  "label-rtl": () => import("./variants/label-rtl.tsx?raw"),
  "loader-button": () => import("./variants/loader-button.tsx?raw"),
  "loader-demo": () => import("./variants/loader-demo.tsx?raw"),
  "loader-size": () => import("./variants/loader-size.tsx?raw"),
  "marker-border": () => import("./variants/marker-border.tsx?raw"),
  "marker-demo": () => import("./variants/marker-demo.tsx?raw"),
  "marker-icon": () => import("./variants/marker-icon.tsx?raw"),
  "marker-link-button": () => import("./variants/marker-link-button.tsx?raw"),
  "marker-separator": () => import("./variants/marker-separator.tsx?raw"),
  "marker-shimmer": () => import("./variants/marker-shimmer.tsx?raw"),
  "marker-status": () => import("./variants/marker-status.tsx?raw"),
  "marker-variants": () => import("./variants/marker-variants.tsx?raw"),
  "menubar-checkbox": () => import("./variants/menubar-checkbox.tsx?raw"),
  "menubar-demo": () => import("./variants/menubar-demo.tsx?raw"),
  "menubar-icons": () => import("./variants/menubar-icons.tsx?raw"),
  "menubar-radio": () => import("./variants/menubar-radio.tsx?raw"),
  "menubar-rtl": () => import("./variants/menubar-rtl.tsx?raw"),
  "menubar-submenu": () => import("./variants/menubar-submenu.tsx?raw"),
  "message-actions": () => import("./variants/message-actions.tsx?raw"),
  "message-attachment": () => import("./variants/message-attachment.tsx?raw"),
  "message-avatar": () => import("./variants/message-avatar.tsx?raw"),
  "message-demo": () => import("./variants/message-demo.tsx?raw"),
  "message-group": () => import("./variants/message-group.tsx?raw"),
  "message-header-footer": () =>
    import("./variants/message-header-footer.tsx?raw"),
  "message-scroller-anchoring": () =>
    import("./variants/message-scroller-anchoring.tsx?raw"),
  "message-scroller-animation": () =>
    import("./variants/message-scroller-animation.tsx?raw"),
  "message-scroller-commands": () =>
    import("./variants/message-scroller-commands.tsx?raw"),
  "message-scroller-demo": () =>
    import("./variants/message-scroller-demo.tsx?raw"),
  "message-scroller-group-chat": () =>
    import("./variants/message-scroller-group-chat.tsx?raw"),
  "message-scroller-load-history": () =>
    import("./variants/message-scroller-load-history.tsx?raw"),
  "message-scroller-opening-position": () =>
    import("./variants/message-scroller-opening-position.tsx?raw"),
  "message-scroller-previous-context": () =>
    import("./variants/message-scroller-previous-context.tsx?raw"),
  "message-scroller-scrollable": () =>
    import("./variants/message-scroller-scrollable.tsx?raw"),
  "message-scroller-streaming": () =>
    import("./variants/message-scroller-streaming.tsx?raw"),
  "message-scroller-visibility": () =>
    import("./variants/message-scroller-visibility.tsx?raw"),
  "native-select-demo": () => import("./variants/native-select-demo.tsx?raw"),
  "native-select-disabled": () =>
    import("./variants/native-select-disabled.tsx?raw"),
  "native-select-groups": () =>
    import("./variants/native-select-groups.tsx?raw"),
  "native-select-invalid": () =>
    import("./variants/native-select-invalid.tsx?raw"),
  "native-select-rtl": () => import("./variants/native-select-rtl.tsx?raw"),
  "navigation-menu-demo": () =>
    import("./variants/navigation-menu-demo.tsx?raw"),
  "navigation-menu-rtl": () => import("./variants/navigation-menu-rtl.tsx?raw"),
  "pagination-custom": () => import("./variants/pagination-custom.tsx?raw"),
  "pagination-demo": () => import("./variants/pagination-demo.tsx?raw"),
  "pagination-dropdown": () => import("./variants/pagination-dropdown.tsx?raw"),
  "pagination-icons-only": () =>
    import("./variants/pagination-icons-only.tsx?raw"),
  "pagination-links": () => import("./variants/pagination-links.tsx?raw"),
  "pagination-rtl": () => import("./variants/pagination-rtl.tsx?raw"),
  "pagination-simple": () => import("./variants/pagination-simple.tsx?raw"),
  "pagination-states": () => import("./variants/pagination-states.tsx?raw"),
  "pagination-unknown-total": () =>
    import("./variants/pagination-unknown-total.tsx?raw"),
  "popover-alignments": () => import("./variants/popover-alignments.tsx?raw"),
  "popover-basic": () => import("./variants/popover-basic.tsx?raw"),
  "popover-demo": () => import("./variants/popover-demo.tsx?raw"),
  "popover-form": () => import("./variants/popover-form.tsx?raw"),
  "popover-rtl": () => import("./variants/popover-rtl.tsx?raw"),
  "progress-controlled": () => import("./variants/progress-controlled.tsx?raw"),
  "progress-demo": () => import("./variants/progress-demo.tsx?raw"),
  "progress-label": () => import("./variants/progress-label.tsx?raw"),
  "progress-rtl": () => import("./variants/progress-rtl.tsx?raw"),
  "questionnaire-animated": () =>
    import("./variants/questionnaire-animated.tsx?raw"),
  "questionnaire-card": () => import("./variants/questionnaire-card.tsx?raw"),
  "questionnaire-conditional": () =>
    import("./variants/questionnaire-conditional.tsx?raw"),
  "questionnaire-controlled": () =>
    import("./variants/questionnaire-controlled.tsx?raw"),
  "questionnaire-demo": () => import("./variants/questionnaire-demo.tsx?raw"),
  "questionnaire-dialog": () =>
    import("./variants/questionnaire-dialog.tsx?raw"),
  "questionnaire-freeform": () =>
    import("./variants/questionnaire-freeform.tsx?raw"),
  "questionnaire-multiple": () =>
    import("./variants/questionnaire-multiple.tsx?raw"),
  "questionnaire-navigation-state": () =>
    import("./variants/questionnaire-navigation-state.tsx?raw"),
  "questionnaire-progress": () =>
    import("./variants/questionnaire-progress.tsx?raw"),
  "questionnaire-resume": () =>
    import("./variants/questionnaire-resume.tsx?raw"),
  "questionnaire-shortcuts": () =>
    import("./variants/questionnaire-shortcuts.tsx?raw"),
  "questionnaire-skip": () => import("./variants/questionnaire-skip.tsx?raw"),
  "questionnaire-validation": () =>
    import("./variants/questionnaire-validation.tsx?raw"),
  "radio-group-choice-card": () =>
    import("./variants/radio-group-choice-card.tsx?raw"),
  "radio-group-demo": () => import("./variants/radio-group-demo.tsx?raw"),
  "radio-group-description": () =>
    import("./variants/radio-group-description.tsx?raw"),
  "radio-group-disabled": () =>
    import("./variants/radio-group-disabled.tsx?raw"),
  "radio-group-fieldset": () =>
    import("./variants/radio-group-fieldset.tsx?raw"),
  "radio-group-invalid": () => import("./variants/radio-group-invalid.tsx?raw"),
  "radio-group-rtl": () => import("./variants/radio-group-rtl.tsx?raw"),
  "resizable-demo": () => import("./variants/resizable-demo.tsx?raw"),
  "resizable-handle": () => import("./variants/resizable-handle.tsx?raw"),
  "resizable-rtl": () => import("./variants/resizable-rtl.tsx?raw"),
  "resizable-vertical": () => import("./variants/resizable-vertical.tsx?raw"),
  "scroll-area-demo": () => import("./variants/scroll-area-demo.tsx?raw"),
  "scroll-area-horizontal-demo": () =>
    import("./variants/scroll-area-horizontal-demo.tsx?raw"),
  "scroll-area-rtl": () => import("./variants/scroll-area-rtl.tsx?raw"),
  "scroll-fade-demo": () => import("./variants/scroll-fade-demo.tsx?raw"),
  "scroll-fade-edge": () => import("./variants/scroll-fade-edge.tsx?raw"),
  "scroll-fade-horizontal": () =>
    import("./variants/scroll-fade-horizontal.tsx?raw"),
  "scroll-fade-none": () => import("./variants/scroll-fade-none.tsx?raw"),
  "scroll-fade-overflow": () =>
    import("./variants/scroll-fade-overflow.tsx?raw"),
  "scroll-fade-rtl": () => import("./variants/scroll-fade-rtl.tsx?raw"),
  "scroll-fade-size": () => import("./variants/scroll-fade-size.tsx?raw"),
  "select-align-item": () => import("./variants/select-align-item.tsx?raw"),
  "select-demo": () => import("./variants/select-demo.tsx?raw"),
  "select-disabled": () => import("./variants/select-disabled.tsx?raw"),
  "select-groups": () => import("./variants/select-groups.tsx?raw"),
  "select-invalid": () => import("./variants/select-invalid.tsx?raw"),
  "select-rtl": () => import("./variants/select-rtl.tsx?raw"),
  "select-scrollable": () => import("./variants/select-scrollable.tsx?raw"),
  "sensitive-input-controlled": () =>
    import("./variants/sensitive-input-controlled.tsx?raw"),
  "sensitive-input-demo": () =>
    import("./variants/sensitive-input-demo.tsx?raw"),
  "sensitive-input-states": () =>
    import("./variants/sensitive-input-states.tsx?raw"),
  "separator-demo": () => import("./variants/separator-demo.tsx?raw"),
  "separator-list": () => import("./variants/separator-list.tsx?raw"),
  "separator-menu": () => import("./variants/separator-menu.tsx?raw"),
  "separator-rtl": () => import("./variants/separator-rtl.tsx?raw"),
  "separator-vertical": () => import("./variants/separator-vertical.tsx?raw"),
  "sheet-demo": () => import("./variants/sheet-demo.tsx?raw"),
  "sheet-no-close-button": () =>
    import("./variants/sheet-no-close-button.tsx?raw"),
  "sheet-rtl": () => import("./variants/sheet-rtl.tsx?raw"),
  "sheet-side": () => import("./variants/sheet-side.tsx?raw"),
  "shimmer-angle": () => import("./variants/shimmer-angle.tsx?raw"),
  "shimmer-color": () => import("./variants/shimmer-color.tsx?raw"),
  "shimmer-demo": () => import("./variants/shimmer-demo.tsx?raw"),
  "shimmer-duration": () => import("./variants/shimmer-duration.tsx?raw"),
  "shimmer-marker": () => import("./variants/shimmer-marker.tsx?raw"),
  "shimmer-none": () => import("./variants/shimmer-none.tsx?raw"),
  "shimmer-once": () => import("./variants/shimmer-once.tsx?raw"),
  "shimmer-rtl": () => import("./variants/shimmer-rtl.tsx?raw"),
  "shimmer-spread": () => import("./variants/shimmer-spread.tsx?raw"),
  "sidebar-demo": () => import("./variants/sidebar-demo.tsx?raw"),
  "skeleton-avatar": () => import("./variants/skeleton-avatar.tsx?raw"),
  "skeleton-card": () => import("./variants/skeleton-card.tsx?raw"),
  "skeleton-demo": () => import("./variants/skeleton-demo.tsx?raw"),
  "skeleton-form": () => import("./variants/skeleton-form.tsx?raw"),
  "skeleton-rtl": () => import("./variants/skeleton-rtl.tsx?raw"),
  "skeleton-table": () => import("./variants/skeleton-table.tsx?raw"),
  "skeleton-text": () => import("./variants/skeleton-text.tsx?raw"),
  "slider-controlled": () => import("./variants/slider-controlled.tsx?raw"),
  "slider-demo": () => import("./variants/slider-demo.tsx?raw"),
  "slider-disabled": () => import("./variants/slider-disabled.tsx?raw"),
  "slider-multiple": () => import("./variants/slider-multiple.tsx?raw"),
  "slider-range": () => import("./variants/slider-range.tsx?raw"),
  "slider-rtl": () => import("./variants/slider-rtl.tsx?raw"),
  "slider-vertical": () => import("./variants/slider-vertical.tsx?raw"),
  "switch-choice-card": () => import("./variants/switch-choice-card.tsx?raw"),
  "switch-demo": () => import("./variants/switch-demo.tsx?raw"),
  "switch-description": () => import("./variants/switch-description.tsx?raw"),
  "switch-disabled": () => import("./variants/switch-disabled.tsx?raw"),
  "switch-invalid": () => import("./variants/switch-invalid.tsx?raw"),
  "switch-rtl": () => import("./variants/switch-rtl.tsx?raw"),
  "switch-sizes": () => import("./variants/switch-sizes.tsx?raw"),
  "table-actions": () => import("./variants/table-actions.tsx?raw"),
  "tab-bar-demo": () => import("./variants/tab-bar-demo.tsx?raw"),
  "table-demo": () => import("./variants/table-demo.tsx?raw"),
  "table-footer": () => import("./variants/table-footer.tsx?raw"),
  "table-rtl": () => import("./variants/table-rtl.tsx?raw"),
  "tabs-demo": () => import("./variants/tabs-demo.tsx?raw"),
  "tabs-disabled": () => import("./variants/tabs-disabled.tsx?raw"),
  "tabs-icons": () => import("./variants/tabs-icons.tsx?raw"),
  "tabs-line": () => import("./variants/tabs-line.tsx?raw"),
  "tabs-overflow": () => import("./variants/tabs-overflow.tsx?raw"),
  "tabs-rtl": () => import("./variants/tabs-rtl.tsx?raw"),
  "tabs-segment": () => import("./variants/tabs-segment.tsx?raw"),
  "tabs-vertical": () => import("./variants/tabs-vertical.tsx?raw"),
  "tag-input-demo": () => import("./variants/tag-input-demo.tsx?raw"),
  "tag-input-form": () => import("./variants/tag-input-form.tsx?raw"),
  "tag-input-suggestions": () =>
    import("./variants/tag-input-suggestions.tsx?raw"),
  "tag-input-validation": () =>
    import("./variants/tag-input-validation.tsx?raw"),
  "textarea-button": () => import("./variants/textarea-button.tsx?raw"),
  "textarea-demo": () => import("./variants/textarea-demo.tsx?raw"),
  "textarea-disabled": () => import("./variants/textarea-disabled.tsx?raw"),
  "textarea-field": () => import("./variants/textarea-field.tsx?raw"),
  "textarea-invalid": () => import("./variants/textarea-invalid.tsx?raw"),
  "textarea-rtl": () => import("./variants/textarea-rtl.tsx?raw"),
  "theming-mode-comparison": () =>
    import("./variants/theming-mode-comparison.tsx?raw"),
  "theming-palette-playground": () =>
    import("./variants/theming-palette-playground.tsx?raw"),
  "theming-custom-color": () =>
    import("./variants/theming-custom-color.tsx?raw"),
  "theming-semantic-colors": () =>
    import("./variants/theming-semantic-colors.tsx?raw"),
  "toast-demo": () => import("./variants/toast-demo.tsx?raw"),
  "toast-promise": () => import("./variants/toast-promise.tsx?raw"),
  "toast-types": () => import("./variants/toast-types.tsx?raw"),
  "toggle-demo": () => import("./variants/toggle-demo.tsx?raw"),
  "toggle-disabled": () => import("./variants/toggle-disabled.tsx?raw"),
  "toggle-group-demo": () => import("./variants/toggle-group-demo.tsx?raw"),
  "toggle-group-disabled": () =>
    import("./variants/toggle-group-disabled.tsx?raw"),
  "toggle-group-font-weight-selector": () =>
    import("./variants/toggle-group-font-weight-selector.tsx?raw"),
  "toggle-group-outline": () =>
    import("./variants/toggle-group-outline.tsx?raw"),
  "toggle-group-rtl": () => import("./variants/toggle-group-rtl.tsx?raw"),
  "toggle-group-sizes": () => import("./variants/toggle-group-sizes.tsx?raw"),
  "toggle-group-spacing": () =>
    import("./variants/toggle-group-spacing.tsx?raw"),
  "toggle-group-vertical": () =>
    import("./variants/toggle-group-vertical.tsx?raw"),
  "toggle-outline": () => import("./variants/toggle-outline.tsx?raw"),
  "toggle-rtl": () => import("./variants/toggle-rtl.tsx?raw"),
  "toggle-sizes": () => import("./variants/toggle-sizes.tsx?raw"),
  "toggle-text": () => import("./variants/toggle-text.tsx?raw"),
  "toolbar-demo": () => import("./variants/toolbar-demo.tsx?raw"),
  "toolbar-disabled": () => import("./variants/toolbar-disabled.tsx?raw"),
  "toolbar-search": () => import("./variants/toolbar-search.tsx?raw"),
  "tooltip-demo": () => import("./variants/tooltip-demo.tsx?raw"),
  "tooltip-disabled": () => import("./variants/tooltip-disabled.tsx?raw"),
  "tooltip-keyboard": () => import("./variants/tooltip-keyboard.tsx?raw"),
  "tooltip-rtl": () => import("./variants/tooltip-rtl.tsx?raw"),
  "tooltip-sides": () => import("./variants/tooltip-sides.tsx?raw"),
  "code-viewer-demo": () => import("./variants/code-viewer-demo.tsx?raw"),
  "code-viewer-plain": () => import("./variants/code-viewer-plain.tsx?raw"),
  "code-viewer-streaming": () =>
    import("./variants/code-viewer-streaming.tsx?raw"),
  "diff-viewer-demo": () => import("./variants/diff-viewer-demo.tsx?raw"),
  "diff-viewer-streaming": () =>
    import("./variants/diff-viewer-streaming.tsx?raw"),
  "editor-demo": () => import("./variants/editor-demo.tsx?raw"),
  "editor-preview": () => import("./variants/editor-preview.tsx?raw"),
  "editor-toolbar": () => import("./variants/editor-toolbar.tsx?raw"),
  "glass-composition": () => import("./variants/glass-composition.tsx?raw"),
  "glass-demo": () => import("./variants/glass-demo.tsx?raw"),
  "glass-dynamic": () => import("./variants/glass-dynamic.tsx?raw"),
  "html-viewer-demo": () => import("./variants/html-viewer-demo.tsx?raw"),
  "html-viewer-sandbox": () => import("./variants/html-viewer-sandbox.tsx?raw"),
  "image-viewer-controlled": () =>
    import("./variants/image-viewer-controlled.tsx?raw"),
  "image-viewer-demo": () => import("./variants/image-viewer-demo.tsx?raw"),
  "locale-toggle-demo": () => import("./variants/locale-toggle-demo.tsx?raw"),
  "locale-toggle-select": () =>
    import("./variants/locale-toggle-select.tsx?raw"),
  "markdown-viewer-demo": () =>
    import("./variants/markdown-viewer-demo.tsx?raw"),
  "markdown-viewer-sanitized": () =>
    import("./variants/markdown-viewer-sanitized.tsx?raw"),
  "qr-code-animated": () => import("./variants/qr-code-animated.tsx?raw"),
  "qr-code-demo": () => import("./variants/qr-code-demo.tsx?raw"),
  "qr-code-glass": () => import("./variants/qr-code-glass.tsx?raw"),
  "qr-code-margin": () => import("./variants/qr-code-margin.tsx?raw"),
  "qr-code-logo": () => import("./variants/qr-code-logo.tsx?raw"),
  "qr-code-states": () => import("./variants/qr-code-states.tsx?raw"),
  "theme-toggle-demo": () => import("./variants/theme-toggle-demo.tsx?raw"),
  "theme-toggle-variants": () =>
    import("./variants/theme-toggle-variants.tsx?raw"),
} as const;

export type ExampleSlug = keyof typeof examples;
